# This is a basic workflow to help you get started with Actions

name: My First Workflow

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:

  # Automatic trigger on push events to the main branch
  push:
    branches:
      - master

  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    branches:
      - master

  # Scheduled trigger at 5:00 AM UTC, Monday through Friday
  schedule:
    - cron: '0 5 * * 1-5'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run Test
      run: npm test

    - name: Print a message
      run: echo "Hello, world!"
