# This is a basic workflow to help you get started with Actions

name: My First Workflow

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches: 
     - master
  pull_request:
    branches: 
     - master
  schedule:
    - cron: '0 5 * * 1-5'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Print a message
      run: echo "Hello, world!"